### ISSUE TITLE
Compatibility issue with latest Xcode

### ISSUE THREAD

**Issue by rizwan95** [imdevin567/AirLocatorSwift#1]
First of all thank you so much for writing the iBeacon code in swift. However, the latest Xcode has a lot of syntax changed and hence there are errors in the project files (around 35 errors) please fix them.

**Comment by imdevin567** [comment]
@rizwan95 I apologize for the late response, I haven't been actively following this lately. 

@perlmunger was kind enough to submit a pull request updating to the most recent Swift syntax. Hopefully this fixes your issues.
